### ISSUE TITLE
Все задания по черепашке

### ISSUE THREAD

**Issue by AndreyTyshevich** [AndreyTyshevich/prog_Tyshevich#11]
@antosha417 34c777b50945cb791eb1ae300be37de3b86150de
1525e5674d73642ac9a98ed84d3b93a695eb3831
4a254fc30bd744f01f6b67ae0c8c2d6d12ba7050
66ef57f4589c50eb4ffd9b723d4ae3f55a759b23
fe2d9d727d363e76fc3c9aa13bc0139d3f059320
fed87154f3923f51585721178686cd7d6d079d52
deaca8914dc2073dabecd9f28ccfcb7a74c27dcc
150bf915055250bbfe0a345d1ee1e6696e3e8a95
a2456bbea0d71d883d1d8a804070cb5215169444
d12d51650d78e544a0ca981e35d47dfed5a84bb3

**Comment by antosha417** [comment]
Давай их в папку засунем?

**Comment by antosha417** [comment]
Добавь туда текст заданий, я не понимаю справился ты или нет

**Comment by antosha417** [comment]
Пайчарм ругается на твой кодстайл и несоблюдение пеп8, поправь, пожалуйста.

**Comment by AndreyTyshevich** [comment]
Сделал

**Comment by antosha417** [comment]
Пиши хорошие коммита сообщения, у тебя каждый коммит это add files with upload

**Comment by antosha417** [comment]
Читай регламент

**Comment by antosha417** [comment]
Бесконечные циклы в данной задаче плохо. Представь, что ты попросил у художника что-то нарисовать. Он нарисовал, но тебе управление не отдал, а продолжает бесконечно рисовать. Я так не хочу.

**Comment by antosha417** [comment]
Транслит и однобуквенные переменные тоже плохо

**Comment by AndreyTyshevich** [comment]
@antosha417  поправил
2293ede792e1ba01ab057fb2f10759582a47dbdf
f9858fe720bae566e9bbbc7b66262b42ea4de939
cf8a187e1e9410bdc1149fa38a80e9db68216caa
bbc30ae0bd04f4b3d96f5173eb20a4d0bdb1ad04
db69bb510e67183ecee7e7f60f81f8d57c2b07cc
914709f29f25dad4d7f140b2ffb7f574ed5d8fb6
10e8865bde7095642ffa01afeb649a6d87b5f6e1
5711dd4d5280388004e1394fd6b729dc81043a26

**Comment by antosha417** [comment]
Закрывай issue
