### ISSUE TITLE
Анимация

### ISSUE THREAD

**Issue by AndreyTyshevich** [AndreyTyshevich/prog_Tyshevich#12]
@antosha417 20b94effc2c8d98e4514145ff454f9adbc7b9afb

**Comment by antosha417** [comment]
```while True==True``` говорили об этом на семинаре.

Я бы тебе советовал сначала сдать графику, а потом пробовать анимацию сдаватью. Я не хочу тоже самое писать чтоб ты поправил.

**Comment by AndreyTyshevich** [comment]
@antosha417 5b4fd2068c022c5ed2130416dca68a977aecf52f

**Comment by AndreyTyshevich** [comment]
@antosha417 5b4fd2068c022c5ed2130416dca68a977aecf52f

**Comment by antosha417** [comment]
Пайчарм ругается на твой кодстайл и несоблюдение пеп8, поправь, пожалуйста.
И можешь закрывать issue.
