### ISSUE TITLE
Поймай шарик

### ISSUE THREAD

**Issue by AndreyTyshevich** [AndreyTyshevich/prog_Tyshevich#13]
@antosha417 93eba42d5ce0d846618cb3adc471fe9200458aa8

**Comment by antosha417** [comment]
Нечитаемое название файла.

**Comment by antosha417** [comment]
Пайчарм ругается на твой кодстайл и несоблюдение пеп8, поправь, пожалуйста.

**Comment by antosha417** [comment]
Сделай чтобы можно было только 1 очко с одного шарика заработать

**Comment by AndreyTyshevich** [comment]
@antosha417 43ea3c29d019bc611e26e5f62a26c9f3bf34331a

**Comment by antosha417** [comment]
непонятно по названию файла что в нём

**Comment by antosha417** [comment]
я много раз кликаю на шарик и мне считает это за промахи, грустно

**Comment by antosha417** [comment]
Пока ставлю тебе 0,7  за задачу, чтобы поднять поправь код.

**Comment by AndreyTyshevich** [comment]
@antosha417 6dbd68ed46876d14147049de4ffadd592ac5d2aa

**Comment by AndreyTyshevich** [comment]
@antosha417 e9b8dcad5edae2e0daedd1bce55570befc23b1cd поправил

**Comment by antosha417** [comment]
Добавь комментарии к коду и документацию  где нужно и можешь закрывать
