### ISSUE TITLE
Удали лишние файлы

### ISSUE THREAD

**Issue by antosha417** [AndreyTyshevich/prog_Tyshevich#9]
У тебя одни и те же файлы лежат в разных местах проекта. Зачем?

**Comment by AndreyTyshevich** [comment]
Удалил

**Comment by AndreyTyshevich** [comment]
я не знаю, как можно скинуть кэша удаления файла

**Comment by AndreyTyshevich** [comment]
6975de978bf5d352b667dba9ff3f2a996b23b86e

**Comment by AndreyTyshevich** [comment]
c3109eed8af15e54539c3b7870451d47e389ba74

**Comment by antosha417** [comment]
Хорошо, но мне кажется в репозитории всё равно сложно ориентироваться, может распихаешь файлы по папкам?
